apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-install-hook-deleter
  namespace: {{ .Values.project }}
  annotations:
    "helm.sh/hook": "post-delete, pre-delete"
    "helm.sh/hook-weight": "2"


---
 # pre-install-hook-deleter-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pre-install-hook-deleter-role
  namespace: {{ .Values.project }}
  annotations:
    "helm.sh/hook": "post-delete, pre-delete"
    "helm.sh/hook-weight": "2"
rules:
- apiGroups: ["*"] 
  resources: ["projects", "deployments", "pods", "virtualmachines"] 
  verbs: ["delete", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pre-install-hook-deleter-rolebinding
  namespace: {{ .Values.project }}
  annotations:
    "helm.sh/hook": "post-delete, pre-delete"
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: pre-install-hook-deleter
  namespace: apstra-rhocp-demo-helm
roleRef:
  kind: Role
  name: pre-install-hook-deleter-role
  apiGroup: rbac.authorization.k8s.io
