apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: apstra-rhocp-demo-helm
  labels:
    #type: eda
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
  annotations:
    "helm.sh/hook": "pre-install"
    apstra.juniper.net/vrf: '[
      {
        "vrfName": "vrf-demo-helm"
      }
    ]'
