apiVersion: v1
kind: Service
metadata:
  name: event-notification-service
  namespace: default
  labels:
    app: event-notification-service
spec:
  selector:
    app: event-notification-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
