---
# roles/ntx_delete_virtual_network/defaults/main.yml

# Apstra connection details (should be provided via vault or environment)
apstra_host: ""
apstra_username: ""
apstra_password: ""
apstra_verify_certificates: false

# ConfigMap details for blueprint name
config_map_name: "ansible-tower-config"
config_map_namespace: "default"

# Processing defaults
default_deletion_timeout: 30  # seconds
default_retry_count: 3
default_retry_delay: 5  # seconds

# Event handling
supported_deletion_event_type: "DELETED"
supported_entity_types:
  - "SUBNET"

# Cleanup options
cleanup_configmap: true
cleanup_associated_resources: true
