---
- name: Unlock the blueprint for security 
  when: event.resource.kind in ["Project", "Namespace"]
  block: 
    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Lock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
        lock_state: "unlocked"
      register: register_bp

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit

- name: Unlock the blueprint for sriovnetwork 
  when: event.resource.kind in ["SriovNetwork","NetworkAttachmentDefinition"]
  block: 
    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Unlock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
        lock_state: "unlocked"
      register: register_bp

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit

- name: Unlock the blueprint for Pod
  when: event.resource.kind in ["Pod"]
  block: 
    - name: Get the name of the namespace
      set_fact:
        namespace: "{{ event.resource.metadata.namespace }}"
        
    - name: Get the bluprint name from pod namespace annotations
      k8s_info: 
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
      register: podnamespace_info
      
    - name: Get the annotations of the namespace
      set_fact:
        pod_annotations: "{{ podnamespace_info.resources[0].metadata.annotations }}"
        
    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth
      
    - name: Lock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
        lock_state: "unlocked"
      register: register_bp

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit