---
- name: Listen for Namespace or Pod
  hosts: all
  sources:
    - juniper.eda.k8s:
        kinds:
          - api_version: v1
            kind: Namespace
          - api_version: sriovnetwork.openshift.io/v1
            kind: SriovNetwork
            label_selectors: ["type=eda"]
            ignore_modified_deleted: True
            changed_fields:
              - spec.vlan
          - api_version: v1
            kind: Pod
            label_selectors: ["type=eda"]
  rules:
    - name: Event for EDA Namespace add
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == "eda" and event.resource.kind == "Namespace"
      action:
        run_job_template:
          name: create-vrf
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for SRIOV Network add
      condition: event.type == "ADDED" and event.resource.kind == SriovNetwork
      action:
        run_job_template:
          name: create-vnet
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for PoD add
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == "eda" and event.resource.kind == "Pod"
      action:
        run_job_template:
          name: create-connectivity-template
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Existing Namespaces
      condition: event.type == "INIT_DONE" and event.resources.kind == "NamespaceList"
      action:
        debug:
          msg: "INIT_DONE: Namespaces: {{ event.resources }}"

    - name: Namespace Added/Modified/Deleted
      condition: event.resource.kind == "Namespace"
      action:
        debug:
          msg: "{{ event.type }}: Namespace {{ event.resource.metadata.name }}"

    - name: Existing Pods
      condition: event.type == "INIT_DONE" and event.resources.kind == "PodList"
      action:
        debug:
          msg: "INIT_DONE: Pods: {{ event.resources }}"
