---
- name: Listen for Namespace or Pod
  hosts: all
  sources:
    - juniper.eda.k8s:
        heartbeat_interval: 120
        kinds:
          - api_version: v1
            kind: Namespace
          - api_version: sriovnetwork.openshift.io/v1
            kind: SriovNetwork
            ignore_modified_deleted: true
            changed_fields:
              - spec.vlan
          - api_version: v1
            kind: Pod
            label_selectors: ["type=eda"]
  rules:
    - name: Event for EDA Namespace add
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == eda and event.resource.kind == Namespace
      action:
        run_job_template:
          name: create-vrf
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for sriovnet add
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == eda and event.resource.kind == SriovNetwork
      action:
        run_job_template:
          name: create-vnet
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for PoD add
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == eda and event.resource.kind == Pod
      action:
        run_job_template:
          name: create-connectivity-template
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for NS delete
      condition: event.type == "DELETED" and event.resource.metadata.labels.type == eda and event.resource.kind == Namespace
      action:
        run_job_template:
          name: delete-vrf
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for sriovnet delete
      condition: event.type == "DELETED" and event.resource.metadata.labels.type == eda and event.resource.kind == SriovNetwork
      action:
        run_job_template:
          name: delete-vnet
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for PoD delete
      condition: event.type == "DELETED" and event.resource.metadata.labels.type == eda and event.resource.kind == Pod
      action:
        run_job_template:
          name: delete-connectivity-template
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Event for sriovnet modified
      condition: event.type == "MODIFIED" and event.resource.metadata.labels.type == eda and event.resource.kind == SriovNetwork
      action:
        run_job_template:
          name: create-vnet
          organization: Default
          job_args:
            extra_vars:
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
              bp: "{{ blueprint_name }}"

    - name: Init Done event
      condition: event.type == "INIT_DONE"
      action:
        run_job_template:
          name: init-done
          organization: Default
          job_args:
            extra_vars:
              init_ev: "{{ event }}"
              bp: "{{ blueprint_name }}"
