---
- name: Test create/delete blueprint
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Connect to Apstra
      juniper.apstra.authenticate:
        logout: false
      register: auth

    - name: Get blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
        lock_state: "ignore"
      register: register_bp

    - name: Show blueprint
      ansible.builtin.debug:
        var: register_bp

    - name: Delete blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        state: absent
        auth_token: "{{ auth.token }}"
      register: blueprint_delete

    - name: Show deleted blueprint
      ansible.builtin.debug:
        var: blueprint_delete
