# roles/lock_blueprint/tasks/main.yml
---
- name: Lock the blueprint for security 
  when: event.resource.kind in ["Project", "Namespace"]
  block: 
    - name: print blurprint_name
      debug:
        msg: "{{ blueprint_name }}"

    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Lock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
      register: register_bp

    - name: Print register_bp
      debug:
        msg: "{{ register_bp }}"

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit

- name: Lock the blueprint for sriovnetwork 
  when: event.resource.kind in ["SriovNetwork","NetworkAttachmentDefinition"]
  block: 
    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Lock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
      register: register_bp

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit

- name: Lock the blueprint for Pod
  when: event.resource.kind in ["Pod"]
  block: 
    - name: Set the blueprint name
      set_fact:
        bluprint_label_value: "{{ blueprint_name }}"

    - name: Connect to Apstra
      juniper.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth
      
    - name: Lock blueprint
      juniper.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
      register: register_bp

    - name: Commit the blueprint
      juniper.apstra.blueprint:
        id: "{{ register_bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit